"""The shop harness's verb table (kit.verbs): every command it answers,
and what kind of thing each does."""

from kit.verbs import Verb

VERBS = [
    Verb(("facts", "init"), "facts.py", "human", False,
         answers="Declare a market and answer the onboarding questions"),
    Verb(("facts", "list"), "facts.py", "read",
         answers="Every fact of a market (* = pending)",
         examples=("facts list --json",
                   "facts list --market US --pending --json"),
         keys=("declared_markets", "pending_markets", "facts")),
    Verb(("facts", "get"), "facts.py", "read", answers="One fact"),
    Verb(("facts", "history"), "facts.py", "read",
         answers="Who changed which fact, when and why"),
    Verb(("facts", "set"), "facts.py", "human",
         answers="Record a value, pending until a person confirms it"),
    Verb(("facts", "unconfirm"), "facts.py", "human",
         answers="Doubt a confirmed value (lowers trust)"),
    Verb(("facts", "rollback"), "facts.py", "human",
         answers="Propose an earlier value again, pending"),
    Verb(("facts", "confirm"), "facts.py", "gated",
         answers="A person confirms a pending value",
         examples=("facts confirm unit_cost --market US --reason invoice",
                   "facts confirm unit_cost --market US --reason invoice "
                   "--code 123456 --relay-user chat:U1 --relay-at "
                   "2026-09-23T10:00:00Z --json",
                   "facts confirm unit_cost --market US --reason call "
                   "--for-client Acme --json"),
         keys=("confirmed", "changed_by", "reason", "message")),
    Verb(("facts", "restore"), "facts.py", "gated", False,
         answers="Replay a backup (a person at the terminal)"),
    Verb(("decisions", "list"), "decisions.py", "read",
         answers="Every decision (* = pending)"),
    Verb(("decisions", "get"), "decisions.py", "read",
         answers="One decision and the value in force"),
    Verb(("decisions", "history"), "decisions.py", "read",
         answers="Every change to a decision"),
    Verb(("decisions", "set"), "decisions.py", "human",
         answers="Propose a decision, pending"),
    Verb(("decisions", "withdraw"), "decisions.py", "human",
         answers="Take back a pending decision"),
    Verb(("decisions", "confirm"), "decisions.py", "gated",
         answers="A person puts a decision in force"),
    Verb(("pending",), "pending.py", "read",
         answers="What waits on a person, as ready console asks",
         examples=("pending --json",)),
    Verb(("compute", "steer"), "compute_steer.py", "read",
         answers="Which restock to make now, as proposals"),
    Verb(("queue", "list"), "queue.py", "read",
         answers="Queued proposals and their status"),
    Verb(("queue", "add"), "queue.py", "human",
         answers="Queue the current proposals, pending a person's yes"),
    Verb(("queue", "reject"), "queue.py", "human",
         answers="Say no to a proposal, with a reason code"),
    Verb(("queue", "approve"), "queue.py", "gated",
         answers="A person approves a proposal"),
    Verb(("execute", "apply"), "execute_actions.py", "external",
         answers="Send approved items (a dry run unless --apply)"),
    Verb(("execute", "reconcile"), "execute_actions.py", "external",
         answers="Read back an item whose outcome is unknown"),
]
